#!/usr/bin/env bash

screen_height="$(xrandr | grep '*' | awk 'NR==1{print $1}' | cut -d 'x' -f '2')"

font_text='JetBrains Mono NF'
font_icons='Font Awesome 6 Free Solid'
font_size=$((screen_height / 70))
border=$((screen_height / 300))

export POLYBAR_FONT_TEXT="$font_text:size=$font_size;$((screen_height / 275))"
export POLYBAR_FONT_ICONS="$font_icons:size=$font_size;$((screen_height / 275))"
export POLYBAR_BORDER="$border"

export ROFI_FONT_RUN="\"$font_text $font_size\""
export ROFI_FONT_POWER="\"$font_icons $((screen_height / 25))\""
export ROFI_BORDER="$border"
export ROFI_PADDING_SMALL=$((screen_height / 150))
export ROFI_PADDING_BIG=$((ROFI_PADDING_SMALL * 2))
export ROFI_WIDTH_POWER="calc($((2 * (ROFI_BORDER + ROFI_PADDING_BIG) + 12 * ROFI_PADDING_BIG)) + 6em + 0.6%)"

export WEZTERM_FONT_SIZE="$font_size"

cat << EOF | xrdb -merge
I3_BORDER: $border
I3_GAPS:   $((screen_height / 50))
EOF

"$XDG_STATE_HOME/fehbg"
i3
